### ISSUE TITLE
Throws when run in a project without a package.json

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/clinton#45]
```
SublimeLinter-contrib-xo
TypeError: Cannot read property 'clinton' of undefined
    at /usr/local/lib/node_modules/clinton/lib/config.js:21:59
```

**Comment by SamVerschueren** [comment]
Good point, never ran in on such projects.

**Comment by beatfreaker** [comment]
can i help with this?

**Comment by SamVerschueren** [comment]
> can i help with this?

You can, but I think quite some things have to be changed for this. I'm always open for a good PR.

**Comment by beatfreaker** [comment]
I have not dig deep into it but i think we should throw `err` from here https://github.com/SamVerschueren/clinton/blob/master/lib/config.js#L21 if no `package.json` found

am i right?

**Comment by SamVerschueren** [comment]
The question is, should we still lint if no `package.json` is present?

**Comment by beatfreaker** [comment]
i think we should, it will then lint only on the basis of `opts`

**Comment by SamVerschueren** [comment]
I believe `clinton` will still fail on rules depending on `package.json` like [this](https://github.com/SamVerschueren/clinton/blob/master/rules/pkg-normalize.js#L31) one. Might have to check if `package.json` exists, like I did in the [travis](https://github.com/SamVerschueren/clinton/blob/master/rules/travis.js#L71) rule.

Should we add something like `metadata` to every rule? Little bit like ESLint which will define some dependencies or something. So you can specify which files should be present in order to execute the rule.

Just brainstorming here. Would like some more opinions on how we can solve this elegantly.

**Comment by SamVerschueren** [comment]
I'm ignoring projects without `package.json` for now. I'm open for suggestions on how to improve for projects with `package.json`. But my main focus is JavaScript projects.
